#' Ground Truth Labels of Example Multi-modal Dataset
#'
#' Ground truth sample labels of the synthetic multi-modal dataset generated by 
#' \code{\link{example_MultiModalData_sim}}.
#'
#' @format A character vector that consists of 50 \code{"group 1"}, 
#' 50 \code{"group 2"}, ... , 50 \code{"group 6"} in order.
#'
#' @seealso \code{\link{example_MultiModalData_sim}}
"example_MultiModalData_labels"


