# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logit <- function(p) {
    .Call(`_GPCCA_logit`, p)
}

sigmoid <- function(X) {
    .Call(`_GPCCA_sigmoid`, X)
}

softplus <- function(X) {
    .Call(`_GPCCA_softplus`, X)
}

Q_rcpp0 <- function(param_vec, Y, Z_samples, lambda, n, m, d, S) {
    .Call(`_GPCCA_Q_rcpp0`, param_vec, Y, Z_samples, lambda, n, m, d, S)
}

G_rcpp0 <- function(param_vec, Y, Z_samples, lambda, n, m, d, S) {
    .Call(`_GPCCA_G_rcpp0`, param_vec, Y, Z_samples, lambda, n, m, d, S)
}

Q_rcpp1 <- function(param_vec, Y, Z_samples, lambda, n, m, d, S, ind_M, mu_t, W_t) {
    .Call(`_GPCCA_Q_rcpp1`, param_vec, Y, Z_samples, lambda, n, m, d, S, ind_M, mu_t, W_t)
}

G_rcpp1 <- function(param_vec, Y, Z_samples, lambda, n, m, d, S, ind_M, mu_t, W_t) {
    .Call(`_GPCCA_G_rcpp1`, param_vec, Y, Z_samples, lambda, n, m, d, S, ind_M, mu_t, W_t)
}

Q_W_rcpp0 <- function(W_vec, mu, Y, Z_samples, lambda, n, m, d, S) {
    .Call(`_GPCCA_Q_W_rcpp0`, W_vec, mu, Y, Z_samples, lambda, n, m, d, S)
}

G_W_rcpp0 <- function(W_vec, mu, Y, Z_samples, lambda, n, m, d, S) {
    .Call(`_GPCCA_G_W_rcpp0`, W_vec, mu, Y, Z_samples, lambda, n, m, d, S)
}

Q_W_rcpp1 <- function(W_vec, mu, Y, Z_samples, lambda, n, m, d, S, ind_M, W_t) {
    .Call(`_GPCCA_Q_W_rcpp1`, W_vec, mu, Y, Z_samples, lambda, n, m, d, S, ind_M, W_t)
}

G_W_rcpp1 <- function(W_vec, mu, Y, Z_samples, lambda, n, m, d, S, ind_M, W_t) {
    .Call(`_GPCCA_G_W_rcpp1`, W_vec, mu, Y, Z_samples, lambda, n, m, d, S, ind_M, W_t)
}

armaInv <- function(X) {
    .Call(`_GPCCA_armaInv`, X)
}

tcprod <- function(x) {
    .Call(`_GPCCA_tcprod`, x)
}

fCore_missingF <- function(E_z, E_x, M, n, m, d) {
    .Call(`_GPCCA_fCore_missingF`, E_z, E_x, M, n, m, d)
}

fCore_default0 <- function(X, ind_O, ind_M, tW, mu, Psi, n, m, d) {
    .Call(`_GPCCA_fCore_default0`, X, ind_O, ind_M, tW, mu, Psi, n, m, d)
}

fCore_default1 <- function(X, ind_O, ind_M, tW, mu, Psi, n, m, d, N_ms, ms_index) {
    .Call(`_GPCCA_fCore_default1`, X, ind_O, ind_M, tW, mu, Psi, n, m, d, N_ms, ms_index)
}

diagInv <- function(X) {
    .Call(`_GPCCA_diagInv`, X)
}

fCore_diagcov <- function(X, ind_O, ind_M, tW, mu, Psi, n, m, d) {
    .Call(`_GPCCA_fCore_diagcov`, X, ind_O, ind_M, tW, mu, Psi, n, m, d)
}

